---
- name: set role vars
  set_fact:
    package_name: rofi
    medium: pacman
    config_path: "{{ ansible_facts['user_dir'] }}/.config/rofi"

- name: install package
  include_tasks: ../../../install_package.yml

- name: set config
  include_tasks: ../../../set_config.yml
