---
- name: dotfiles config
  hosts: battlestations

  pre_tasks:
    - name: detect host user
      import_tasks: pre_tasks/whoami.yml
      tags:
        - always

  tasks:
    - name: copy configs to remote
      synchronize:
        src: "."
        dest: "{{ managed_home_path }}"
        mode: push
        delete: true
      when: "ansible_connection != 'local'"
      tags: always

    - name: set roles
      set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags: always

    - name: display roles
      debug:
        var: run_roles
      tags: always

    - name: run roles
      include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags: always