---
- name: setup paths
  set_fact:
    ansible_files_path: "{{ role_path | replace(control_home_path, managed_home_path) }}/files"

- name: list config files
  find:
    path: "{{ ansible_files_path }}"
    recurse: true
    hidden: true
  register: config_list

- name: filter host-specific config files
  set_fact:
    filtered_config_files: >-
      {{
        config_list.files | selectattr('path', 'search', '/common' + config_path.src | default(''))
        + config_list.files | selectattr('path', 'search', '/' + inventory_hostname + config_path.src | default(''))
      }}

- name: backup config files
  block:
  - name: check existing files
    stat:
      path: >-
        {{
         item.path | regex_replace('^' + ansible_files_path + '/(common|' + inventory_hostname + ')'
         + config_path.src | default(''), config_path.dest) 
        }}
    loop: "{{ filtered_config_files }}"
    loop_control:
      label: "{{ item.path }}"
    register: dest_config

  - name: move old files
    command: mv {{ file.stat.path }} {{ file.stat.path }}.old
    loop: "{{ dest_config.results }}"
    loop_control:
      label: "{{ file.item.path }}"
      loop_var: file
    when: file.stat.isreg | default(false) and backup | default(true)
  when: filtered_config_files | length > 0

- name: create directory structure
  file:
    path: "{{ item.invocation.module_args.path | dirname }}" 
    state: directory
    mode: "{{ dir_mode | default('0755')}}"
  loop: "{{ dest_config.results }}"
  loop_control:
    label: "{{ item.invocation.module_args.path | dirname }}" 

- name: create config symlinks
  file:
    src: "{{ item.item.path }}"
    dest: "{{ item.invocation.module_args.path }}"
    state: link
  loop: "{{ dest_config.results }}"
  loop_control:
    label: "{{ item.invocation.module_args.path }}" 
  when: config_path.dest is search(ansible_facts['user_dir'])

- name: copy config files
  copy:
    src: "{{ item.item.path }}"
    dest: "{{ item.invocation.module_args.path }}"
    owner: "{{ owner | default('root') }}"
    mode: "{{ files_mode | default('0644') }}"
  loop: "{{ dest_config.results}}"
  loop_control:
    label: "{{ item.invocation.module_args.path }}" 
  when: config_path.dest is not search(ansible_facts['user_dir'])
