- name: setup arch linux
  hosts: battlestations
  become: true
  tasks:
    - name: update system
      pacman:
        update_cache: true
        upgrade: true

    - name: install essential packages
      pacman:
        name:
          - base-devel
          - dkms
          - git
          - rsync
        state: present
    
    - name: install yay
      include_tasks: install_package.yml
      vars:
        package_name: yay
        medium: aur
      args:
        apply:
          become: false

    - name: install fonts
      pacman:
        name:
          - noto-fonts
          - ttf-jetbrains-mono-nerd

    - name: change default shell to zsh
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh