- name: setup arch linux
  hosts: battlestations
  become: yes
  tasks:
    - name: update system
      pacman:
        update_cache: yes
        upgrade: yes

    - name: install essential packages
      pacman:
        name:
          - base-devel
          - git
          - rsync
        state: present

    - name: install fonts
      pacman:
        name:
          - noto-fonts
          - ttf-jetbrains-mono-nerd

    - name: change default shell to zsh
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh