---
- name: set role vars
  set_fact:
    package_name: netctl
    medium: pacman
    config_path: "/etc/netctl"
    dir_mode: "0700"
    files_mode: "0600"
    
- name: install package
  include_tasks: ../../../install_package.yml

- name: set config
  include_tasks: ../../../set_config.yml
  args:
    apply:
      become: true