---
- name: set role vars
  set_fact:
    package_name: plex-media-server
    medium: aur
    config_path: "/etc/systemd/system"

- name: install package
  include_tasks: ../../../install_package.yml

- name: set config
  include_tasks: ../../../set_config.yml
  args:
    apply:
      become: true