battlestations:
  hosts:
    aero:
      ansible_host: aero
      ansible_user: "{{ aero_user }}"
      ansible_connection: local
      ansible_become_password: "{{ aero_password }}"
    zero: 
      ansible_host: zero
      ansible_user: "{{ zero_user }}"
      ansible_become_password: "{{ zero_password }}"