---
- name: set role vars
  set_fact:
    package_name: visual-studio-code-bin 
    medium: aur
    config_paths:
      - src: "/configs"
        dest: "{{ ansible_facts['user_dir'] }}/.config/Code"
      - src: "/extensions"
        dest: "{{ ansible_facts['user_dir'] }}/.vscode"

- name: install package
  include_tasks: ../../../install_package.yml

- name: set config
  include_tasks: ../../../set_config.yml
  loop: "{{ config_paths }}"
  loop_control:
    loop_var: config_path
  args:
    apply:
      become: "{{ config_path.dest is not search(ansible_facts['user_dir']) }}"