---
- name: "nvim | install latest version"
  pacman:
    name: neovim
    state: present
  become: true
  when: ansible_os_family == "Archlinux"

- name: nvim | set config path
  set_fact: 
     config_path: "{{ ansible_facts['user_dir'] }}/.config/nvim"

- name: set config
  include_tasks: ../../../set_config.yml
