---
- name: set role vars
  set_fact:
    package_name: tealdeer
    medium: pacman
    config_path:
      dest: "{{ ansible_facts['user_dir'] }}/.config/tealdeer"

- name: install package
  include_tasks: ../../../install_package.yml

- name: set config
  include_tasks: ../../../set_config.yml