#!/bin/bash

DOMAIN="reddit.com"
LOCAL_GATEWAY="192.168.88.1"
LOCAL_INTERFACE="wlo1"

IP_ADDRESSES=$(drill A $DOMAIN | sed -n '/ANSWER SECTION:/,/;;/{//!p;}' | awk '{print $5}')

for IP in $IP_ADDRESSES; do
    echo "Excluding $IP from WireGuard tunnel..."
    sudo ip route add $IP via $LOCAL_GATEWAY dev $LOCAL_INTERFACE
done