---
- name: set role vars
  set_fact:
    package_names:
      - i3lock-color 
      - betterlockscreen
    medium: aur
    config_path:
      dest: "{{ ansible_facts['user_dir'] }}/.config/betterlockscreen"

- name: install package
  include_tasks: ../../../install_package.yml
  loop: "{{ package_names }}"
  loop_control:
    loop_var: package_name

- name: set config
  include_tasks: ../../../set_config.yml
