---
- name: dotfiles config
  hosts: battlestations

  pre_tasks:
    - name: detect host user
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

  tasks:
    - name: copy configs to remote
      synchronize:
        src: "."
        dest: "{{ dotfiles_dir }}"
        mode: push
        delete: true
      when: inventory_hostname != 'localhost'

    - name: set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always