- name: Setup Arch Linux
  hosts: local
  become: yes
  tasks:
    - name: Update system
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install essential packages
      pacman:
        name:
          - base-devel
          - git
          - vim
          - zsh
        state: present

    - name: Change default shell to zsh
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh