---
- name: set role vars
  set_fact:
    package_name: docker
    medium: pacman

- name: install package
  include_tasks: ../../../install_package.yml

- name: add group
  group:
    name: docker
    state: present

- name: add user to group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: enable and start services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service