---
- name: set role vars
  set_fact:
    package_names: 
      - bluez
      - bluez-utils
    medium: pacman

- name: install package
  include_tasks: ../../../install_package.yml
  loop: "{{ package_names }}"
  loop_control:
    loop_var: package_name