---
- name: set role vars
  set_fact:
    package_name: wireguard-tools 
    medium: pacman
    config_path: "/etc/wireguard"

- name: install package
  include_tasks: ../../../install_package.yml

- name: set config
  set_fact:
    config_file:
  include_tasks: ../../../set_config.yml
